# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'
target 'SunMediaAds' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  pod 'Smart-Display-SDK'
  pod 'SpotX-SDK'
  pod 'FBAudienceNetwork'
  pod 'FBSDKCoreKit'
  pod 'Google-Mobile-Ads-SDK'
 
end
